resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.17"

resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/vinodameta/microservices-demo.git
    branch: master
 
    #KUBERNETS RESOURSES
- name: kubernetes-test
  type: kubernetes
  source:
    server: https://192.168.99.100:8443
    namespace: default
    insecure_skip_tls_verify: true
    token: {{k8s-token}}

jobs:
- name: kubernetes-deploy-production
  plan:
  - get: tutorial
    trigger: true
  - put: kubernetes-test
    params:
      kubectl: apply -f tutorial/release/adservice.yaml
