apiVersion: batch/v1
kind: Job
metadata:
  name: restore-test-job-16-02-12-16
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo sleeping....; sleep 180s; echo exiting...; date
      restartPolicy: Never
